# Generated by Django 3.0.6 on 2020-11-17 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20201117_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField()),
                ('invoice_amount', models.FloatField()),
                ('taxes', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Solddetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('customer_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Invoice')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
    ]
