# Generated by Django 3.0.6 on 2020-11-20 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solddetails',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
