# Generated by Django 3.0.6 on 2020-11-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_solddetails_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
