# Generated by Django 3.0.6 on 2020-11-15 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('stock_available', models.PositiveIntegerField()),
                ('base_price', models.FloatField()),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductType')),
            ],
        ),
    ]
