# Generated by Django 3.0.6 on 2020-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
